FROM node:16-alpine

ARG MONGO_CONNECTION
ENV MONGO_CONNECTION $MONGO_CONNECTION

ARG DISCORD_TOKEN
ENV DISCORD_TOKEN $DISCORD_TOKEN

ARG URL_JOKE_API
ENV URL_JOKE_API $URL_JOKE_API

RUN apk add --no-cache tzdata
ENV TZ America/Lima

WORKDIR /app
COPY . .
RUN yarn
CMD ["node", "index.js"]
EXPOSE 3000
