FROM node:16-alpine

ARG MONGO_CONNECTION
ENV MONGO_CONNECTION $MONGO_CONNECTION

ARG DISCORD_TOKEN
ENV DISCORD_TOKEN $DISCORD_TOKEN

WORKDIR /app
COPY . .
RUN yarn
CMD ["node", "index.js"]
EXPOSE 3000
